### ISSUE TITLE
Given a domain name, how do I find it's token id?

### ISSUE THREAD

**Issue by diwu1989** [unstoppabledomains/resolution-cli#5]
I have a bunch of unstoppable domain NFT tokens in my polygon wallet, and they have unique token ids.

I want to take a domain name and find its corresponding token id.

**Comment by Noxturnix** [comment]
With resolution-cli:

```
resolution namehash --decimal -d brad.crypto
```

If you want the token ID in hex format, just remove `--decimal` from the command

**Comment by diwu1989** [comment]
ah nice thank you so much!!!
